package sistema_canil;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class JFrameCachorro extends javax.swing.JFrame {

    public JFramePrincipal jfp = new JFramePrincipal();
    public ArrayList<Cachorro> lstc = new ArrayList<Cachorro>();
    
    public JFrameCachorro(ArrayList<Cachorro> lstc, JFramePrincipal jfp) {
        this.jfp = jfp;
        this.lstc = lstc;
        jfp.setEnabled(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCachorroCad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRacaCachorroCad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdadeCachorroCad = new javax.swing.JTextField();
        txtCorCachorroCad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCachorroCad = new javax.swing.JButton();
        btnCachorroLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cachorros");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Cadastro de Cachorros");

        jLabel2.setText("Nome:");

        jLabel3.setText("Raça:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Cor:");

        btnCachorroCad.setText("Cadastrar!");
        btnCachorroCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCachorroCadActionPerformed(evt);
            }
        });

        btnCachorroLimpar.setText("Limpar!");
        btnCachorroLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCachorroLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCachorroLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCachorroCad))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRacaCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdadeCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtCorCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCachorroCad, btnCachorroLimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRacaCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdadeCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorCachorroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCachorroCad)
                    .addComponent(btnCachorroLimpar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        jfp.setEnabled(true);
        jfp.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnCachorroLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCachorroLimparActionPerformed
        txtNomeCachorroCad.setText("");
        txtRacaCachorroCad.setText("");
        txtIdadeCachorroCad.setText("");
        txtCorCachorroCad.setText("");
    }//GEN-LAST:event_btnCachorroLimparActionPerformed

    private void btnCachorroCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCachorroCadActionPerformed
        int idade = 0;
        boolean idadecerta = false;
        if(txtNomeCachorroCad.getText().trim().equals("") || txtRacaCachorroCad.getText().trim().equals("")
                || txtIdadeCachorroCad.getText().trim().equals("") || txtCorCachorroCad.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                idade = Integer.parseInt(txtIdadeCachorroCad.getText());
                idadecerta = true;
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Digite uma Idade Inteira!", "Erro de Idade!", JOptionPane.ERROR_MESSAGE);
                txtIdadeCachorroCad.setText("");
            }
        }
        
        if(idadecerta){
            Cachorro c = new Cachorro();
            c.setNome(txtNomeCachorroCad.getText());
            c.setRaca(txtRacaCachorroCad.getText());
            c.setCor(txtCorCachorroCad.getText());
            c.setIdade(idade);
            lstc.add(c);
            JOptionPane.showMessageDialog(this, "Cachorro Cadastrado com Sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            txtNomeCachorroCad.setText("");
            txtRacaCachorroCad.setText("");
            txtIdadeCachorroCad.setText("");
            txtCorCachorroCad.setText("");
            jfp.recarregarCachorro(lstc.size()-1);   
        }
        
    }//GEN-LAST:event_btnCachorroCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCachorro(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCachorroCad;
    private javax.swing.JButton btnCachorroLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCorCachorroCad;
    private javax.swing.JTextField txtIdadeCachorroCad;
    private javax.swing.JTextField txtNomeCachorroCad;
    private javax.swing.JTextField txtRacaCachorroCad;
    // End of variables declaration//GEN-END:variables
}
